{
 "title": "k6 latency histogram",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(k6_http_reqs)" }
   ]
  },
  {
   "title": "Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(k6_nano_duration_sum{status=\"200\"}[$__range])/sum_over_time(k6_nano_duration_count{status=\"200\"}[$__range])"
    }
   ]
  },
  {
   "title": "med",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(k6_nano_duration_bucket{}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "85%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.85, sum(rate(k6_nano_duration_bucket{}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "95%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_nano_duration_bucket{}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "99,9%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(k6_nano_duration_bucket{}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(k6_nano_duration_bucket{}[$__interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_nano_duration_bucket{}[$__interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(k6_nano_duration_bucket{}[$__interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(k6_nano_duration_bucket[$__range])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg (rate(k6_http_reqs[$__interval]))",
     "legendFormat": "req/sec"
    }
   ]
  },
  {
   "title": "non 200 responses",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(k6_nano_duration_count{status!=\"200\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "non 200 responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(k6_nano_duration_count{status!=\"200\"}[$__interval]) )",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}